export const ROUTES = {
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  bakeries: "/bakeries",
  newBakery: "/bakeries/new",
  bakeryDetail: (id = ":id") => `/bakeries/${id}`,
  editBakery: (id = ":id") => `/bakeries/${id}/edit`,
  users: "/users",
  forms: "/forms",
  newForm: "/forms/new",
  editForm: (id = ":id") => `/forms/${id}/edit`,
  records: "/records",
  newRecord: "/records/new",
  recordDetail: (id = ":id") => `/records/${id}`,
  indicators: "/indicators",
  comparisons: "/comparisons",
  alerts: "/alerts",
  reports: "/reports",
  settings: "/settings",
  audit: "/audit",
} as const;
